export default {
    'REQUEST_PARTS_START': 'REQUEST_PARTS_START',
    'REQUEST_PARTS_DONE': 'REQUEST_PARTS_DONE',
    'REQUEST_PARTS_FAIL': 'REQUEST_PARTS_FAIL',
    
    'ADD_PART': 'ADD_PART',
    'SET_PARTS': 'SET_PARTS',
    'SET_PART': 'SET_PART',
    'EDIT_PART': 'EDIT_PART',
    'DELETE_PART': 'DELETE_PART'
}